<a href="https://colab.research.google.com/github/marcoapedroza/python-stock-analysis-ML-AI/blob/main/predictingStockPrices_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predicting Stock Prices - Deep Learning Model

## Understand the problem statement and business case:
*   In this project, I will train a **deep neural network model** to predict future stock prices;
*   The AI model will be trained using **historical stock price** data along with the **volume** of transactions;
*   I will use a type of neural nets known as **Long Short-Term Memory Networks (LSTM).**

- **LSTM Model** is a **Recurrent Neural Network (RNN)**;
- It has a **feedback loop** that is designed to take temporal dimension into consideration;
- **Feedback Loop: A hidden layer** that gives an output and feeds itself;
- **RNNs** allow us to work with a sequence of **inputs, outputs, and both**.

### Import datasets and libraries:

In [ ]:
import pandas as pd
import plotly.express as px
import seaborn as sns
from copy import copy
from scipy import stats
import matplotlib.pyplot as plt
import numpy as np
import plotly.figure_factory as ff
import yfinance as yf
from tensorflow import keras
import warnings
warnings.filterwarnings('ignore')

In [ ]:
tickers = 'ABEV3.SA B3SA3.SA BBDC3.SA BRKM5.SA CCRO3.SA ELET3.SA EMBR3.SA MGLU3.SA LAME4.SA PETR3.SA'
ticker = '^BVSP'

# Adjusted Close Stock Prices
bovespa = yf.download(ticker, start="2013-01-01")['Adj Close']
stock_prices = yf.download(tickers, start="2013-01-01")['Adj Close']
stock_prices.dropna(how='all', inplace=True)
stock_prices = pd.merge(stock_prices, bovespa, on='Date')
stock_prices.columns = ['ABEV3', 'B3SA3', 'BBDC3', 'BRKM5', 'CCRO3', 'ELET3', 'EMBR3', 'LAME4', 'MGLU3', 'PETR3', 'BOVESPA']
stock_prices

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  10 of 10 completed


ABEV3      B3SA3      BBDC3  ...      MGLU3      PETR3       BOVESPA
Date                                         ...                                    
2013-01-02  12.468795  10.506537  11.001677  ...   0.362545  17.815228   62550.00000
2013-01-03  12.689861  10.506537  11.605797  ...   0.377499  18.479706   63312.00000
2013-01-04  12.480665  10.312937  11.577574  ...   0.375242  18.542559   62523.00000
2013-01-07  12.624581  10.260814  11.304679  ...   0.366495  18.300117   61933.00000
2013-01-08  12.609744  10.350169  11.267038  ...   0.363956  17.779306   61128.00000
...               ...        ...        ...  ...        ...        ...           ...
2021-02-26  14.020000  54.299999  20.572170  ...  24.180000  22.150000  110035.00000
2021-03-01  13.770000  54.349998  19.902750  ...  24.549999  22.010000  110335.00000
2021-03-02  13.990000  56.009998  20.250000  ...  24.270000  21.910000  111540.00000
2021-03-03  14.170000  56.590000  20.660000  ...  25.120001  20.969999  111184.00000
2021-03-04  14.640000  55.549999  21.500000  ...  25.200001  21.850000  113566.40625

[2018 rows x 11 columns]

In [ ]:
# Checking null values
stock_prices.isnull().sum()

ABEV3      0
B3SA3      0
BBDC3      0
BRKM5      0
CCRO3      0
ELET3      0
EMBR3      0
LAME4      0
MGLU3      0
PETR3      0
BOVESPA    0
dtype: int64

In [ ]:
stock_prices.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2018 entries, 2013-01-02 to 2021-03-04
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   ABEV3    2018 non-null   float64
 1   B3SA3    2018 non-null   float64
 2   BBDC3    2018 non-null   float64
 3   BRKM5    2018 non-null   float64
 4   CCRO3    2018 non-null   float64
 5   ELET3    2018 non-null   float64
 6   EMBR3    2018 non-null   float64
 7   LAME4    2018 non-null   float64
 8   MGLU3    2018 non-null   float64
 9   PETR3    2018 non-null   float64
 10  BOVESPA  2018 non-null   float64
dtypes: float64(11)
memory usage: 189.2 KB


In [ ]:
stock_prices.describe()

ABEV3        B3SA3  ...        PETR3        BOVESPA
count  2018.000000  2018.000000  ...  2018.000000    2018.000000
mean     15.383121    22.011867  ...    17.681822   70731.557684
std       2.420674    15.484590  ...     6.648659   21828.284796
min      10.694901     7.134462  ...     5.541526   37497.000000
25%      12.901473     9.715415  ...    12.939808   52442.500000
50%      15.737720    16.564059  ...    15.851011   62840.500000
75%      16.943798    29.620212  ...    22.303133   86945.500000
max      22.276297    65.891556  ...    32.011372  125077.000000

[8 rows x 11 columns]

In [ ]:
ticker_list = ['ABEV3.SA', 'B3SA3.SA', 'BBDC3.SA', 'BRKM5.SA', 'CCRO3.SA', 'ELET3.SA', 'EMBR3.SA', 'LAME4.SA', 'MGLU3.SA', 'PETR3.SA', '^BVSP']
stock_volumes = {}
for i in ticker_list:
  stock = yf.Ticker(i)
  stock_volumes[i] = stock.history(start="2013-01-01")['Volume']

stock_volumes = pd.DataFrame(stock_volumes)
stock_volumes.columns = ['ABEV3', 'B3SA3', 'BBDC3', 'BRKM5', 'CCRO3', 'ELET3', 'EMBR3', 'LAME4', 'MGLU3', 'PETR3', 'BOVESPA']
stock_volumes

ABEV3       B3SA3  ...       PETR3     BOVESPA
Date                                ...                        
2013-01-02   1126114.0  11064300.0  ...  10258500.0   3739800.0
2013-01-03   1032105.0   8380900.0  ...   7823900.0   3355800.0
2013-01-04   1488651.0  13990200.0  ...  16028100.0   6233800.0
2013-01-07   1223124.0   7149400.0  ...  10473900.0   3985800.0
2013-01-08   1103112.0  12690100.0  ...  10505300.0   3840600.0
...                ...         ...  ...         ...         ...
2021-02-26  33969400.0  29567900.0  ...  47419800.0  14618500.0
2021-03-01  19850200.0  14192200.0  ...  40852500.0  11239900.0
2021-03-02  42904000.0  35949300.0  ...  52848600.0  14823200.0
2021-03-03  40193500.0  31255500.0  ...  55664000.0  15144300.0
2021-03-04   8309900.0  10830000.0  ...  12381300.0         0.0

[2025 rows x 11 columns]

In [ ]:
stock_volumes.isna().sum()

ABEV3      1
B3SA3      1
BBDC3      1
BRKM5      1
CCRO3      1
ELET3      1
EMBR3      1
LAME4      1
MGLU3      1
PETR3      1
BOVESPA    7
dtype: int64

In [ ]:
stock_volumes = stock_volumes.dropna()
stock_volumes

ABEV3       B3SA3  ...       PETR3     BOVESPA
Date                                ...                        
2013-01-02   1126114.0  11064300.0  ...  10258500.0   3739800.0
2013-01-03   1032105.0   8380900.0  ...   7823900.0   3355800.0
2013-01-04   1488651.0  13990200.0  ...  16028100.0   6233800.0
2013-01-07   1223124.0   7149400.0  ...  10473900.0   3985800.0
2013-01-08   1103112.0  12690100.0  ...  10505300.0   3840600.0
...                ...         ...  ...         ...         ...
2021-02-26  33969400.0  29567900.0  ...  47419800.0  14618500.0
2021-03-01  19850200.0  14192200.0  ...  40852500.0  11239900.0
2021-03-02  42904000.0  35949300.0  ...  52848600.0  14823200.0
2021-03-03  40193500.0  31255500.0  ...  55664000.0  15144300.0
2021-03-04   8309900.0  10830000.0  ...  12381300.0         0.0

[2018 rows x 11 columns]

In [ ]:
stock_volumes.describe()

ABEV3         B3SA3  ...         PETR3       BOVESPA
count  2.018000e+03  2.018000e+03  ...  2.018000e+03  2.018000e+03
mean   1.548507e+07  1.193593e+07  ...  1.418708e+07  4.721757e+06
std    1.447456e+07  9.097548e+06  ...  1.345056e+07  2.584210e+06
min    0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
25%    8.658622e+06  7.421600e+06  ...  7.563800e+06  3.194525e+06
50%    1.269940e+07  1.016950e+07  ...  1.111720e+07  3.902400e+06
75%    1.953888e+07  1.404008e+07  ...  1.654972e+07  5.188125e+06
max    2.876952e+08  2.072703e+08  ...  3.104194e+08  2.176870e+07

[8 rows x 11 columns]

# Preparing the data before training the AI model:



*   Data set is divided into 70% for training and 30% for testing:
 * Training Set: used for model training;
 * Testing Set: used for testing trained model. It has never been seen by the trained model before.

In [ ]:
# Function to concatenate the stock price, and volume in one dataframe
def concat_stock(price, volume, name):
  return pd.DataFrame({'Close': price[name], 'Volume': volume[name]})

In [ ]:
# Today, the target stock price will be tomorrow's price
# Function that returns a target data for AI/ML model
def target(data):
  # 1 day window
  n = 1
  # Create a column containing the prices for the 'next 1' days
  # Shifts my data by n number of samples, backwards
  data['Target'] = data[['Close']].shift(-n)

  return data

In [ ]:
# Testing the function and getting individual stock prices and volumes for CCRO3
grupoCCR = concat_stock(stock_prices, stock_volumes, 'CCRO3')
grupoCCR

Close      Volume
Date                             
2013-01-02  13.490131   3288600.0
2013-01-03  13.730900   2501600.0
2013-01-04  13.971669   4681500.0
2013-01-07  13.957504   3609400.0
2013-01-08  13.950422   4516000.0
...               ...         ...
2021-02-26  11.250000  19692800.0
2021-03-01  10.920000   8929400.0
2021-03-02  10.880000  17453500.0
2021-03-03  11.030000  14031200.0
2021-03-04  11.490000   4521200.0

[2018 rows x 2 columns]

In [ ]:
# Getting the close and volume data as training data (input) - PRICE AND VOLUME
trainingCCR = grupoCCR.values
trainingCCR

array([[1.34901314e+01, 3.28860000e+06],
       [1.37308998e+01, 2.50160000e+06],
       [1.39716692e+01, 4.68150000e+06],
       ...,
       [1.08800001e+01, 1.74535000e+07],
       [1.10299997e+01, 1.40312000e+07],
       [1.14899998e+01, 4.52120000e+06]])

In [ ]:
# Normalize
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0, 1))
trainingCCR_set_scaled = sc.fit_transform(trainingCCR)
trainingCCR_set_scaled

array([[0.52836366, 0.02629407],
       [0.54780356, 0.0200016 ],
       [0.56724353, 0.03743103],
       ...,
       [0.31761891, 0.13954983],
       [0.32973004, 0.11218676],
       [0.36687092, 0.03614935]])

In [ ]:
# Creating the training and testing data, training data contains present day and previous day values
X = []
y = []


for i in range(1, len(grupoCCR)):

  X.append(trainingCCR_set_scaled[i-1:i, 0])
  y.append(trainingCCR_set_scaled[i, 0])

X[0:5]

[array([0.52836366]),
 array([0.54780356]),
 array([0.56724353]),
 array([0.56609984]),
 array([0.56552803])]

In [ ]:
y[0:5]

[0.5478035558909363,
 0.5672435300187112,
 0.5660998390686,
 0.5655280320938793,
 0.5672435300187112]

In [ ]:
# To convert the data into array format
X = np.asarray(X)
y = np.asarray(y)
print(f'X shape:{X.shape} \ny shape:{y.shape}')

X shape:(2017, 1) 
y shape:(2017,)


In [ ]:
# Splitting the data training - testing
split = int(0.7 * len(X))
X_train = X[:split]
y_train = y[:split]
X_test = X[split:]
y_test = y[split:]
print(f'X_train shape:{X_train.shape} \ny_train shape:{y_train.shape}')

X_train shape:(1411, 1) 
y_train shape:(1411,)


In [ ]:
print(f'X_test shape:{X_test.shape} \ny_test shape:{y_test.shape}')

X_test shape:(606, 1) 
y_test shape:(606,)


In [ ]:
# Reshaping the dimention - 1D --> 3D array - to feed in the LSMT
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
X_train.shape, X_test.shape

((1411, 1, 1), (606, 1, 1))

In [ ]:
# Creating the model
inputs = keras.layers.Input(shape = (X_train.shape[1], X_train.shape[2]))

x = keras.layers.LSTM(150, return_sequences=True)(inputs)
x = keras.layers.LSTM(150, return_sequences=True)(x)
x = keras.layers.LSTM(150, return_sequences=True)(x)

outputs = keras.layers.Dense(1, activation='linear')(x)

model = keras.Model(inputs = inputs, outputs = outputs)
model.compile(optimizer = 'adam', loss = 'mse')
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 1, 1)]            0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 1, 150)            91200     
_________________________________________________________________
lstm_4 (LSTM)                (None, 1, 150)            180600    
_________________________________________________________________
lstm_5 (LSTM)                (None, 1, 150)            180600    
_________________________________________________________________
dense_1 (Dense)              (None, 1, 1)              151       
Total params: 452,551
Trainable params: 452,551
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# Training the model
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
36/36 [==============================] - 7s 56ms/step - loss: 0.1657 - val_loss: 0.0240
Epoch 2/20
36/36 [==============================] - 0s 12ms/step - loss: 0.0076 - val_loss: 0.0204
Epoch 3/20
36/36 [==============================] - 0s 13ms/step - loss: 0.0053 - val_loss: 0.0152
Epoch 4/20
36/36 [==============================] - 0s 13ms/step - loss: 0.0037 - val_loss: 0.0090
Epoch 5/20
36/36 [==============================] - 0s 12ms/step - loss: 0.0022 - val_loss: 0.0037
Epoch 6/20
36/36 [==============================] - 0s 13ms/step - loss: 9.4768e-04 - val_loss: 0.0011
Epoch 7/20
36/36 [==============================] - 0s 13ms/step - loss: 6.1042e-04 - val_loss: 7.0251e-04
Epoch 8/20
36/36 [==============================] - 0s 12ms/step - loss: 5.9435e-04 - val_loss: 6.1038e-04
Epoch 9/20
36/36 [==============================] - 0s 12ms/step - loss: 5.2180e-04 - val_loss: 5.9677e-04
Epoch 10/20
36/36 [==============================] - 0s 12ms/step - loss: 6.4642e

In [ ]:
# Making a prediction
predicted = model.predict(X)

In [ ]:
df_predicted = grupoCCR[1:][['Close']]


# trainingCCR_set_scaled - where the original prices were
close = []

for i in trainingCCR_set_scaled:
  close.append(i[0])


# To append the predicted values to a list
test_predicted = []

for i in predicted:
  test_predicted.append(i[0][0])


In [ ]:
df_predicted['Close'] = close[1:]
df_predicted['Predictions'] = test_predicted
df_predicted

Close  Predictions
Date                             
2013-01-03  0.547804     0.530223
2013-01-04  0.567244     0.550071
2013-01-07  0.566100     0.570087
2013-01-08  0.565528     0.568905
2013-01-09  0.567244     0.568314
...              ...          ...
2021-02-26  0.347493     0.371113
2021-03-01  0.320849     0.353656
2021-03-02  0.317619     0.328877
2021-03-03  0.329730     0.325895
2021-03-04  0.366871     0.337102

[2017 rows x 2 columns]

In [ ]:
# Function to plot interactive plots using Plotly Express
def interactive_plot(df, title):
  fig = px.line(title = title)
  for i in df.columns:
    fig.add_scatter(x = df.index, y = df[i], name = i)
  
  fig.show()

In [ ]:
interactive_plot(df_predicted, 'Original Price vs. LSTM Predictions')